### ISSUE TITLE
Information about CTB and heightmap-1.0 terrain format 

### ISSUE THREAD

**Issue by Jule-** [geo-data/cesium-terrain-builder#12]
I don't understand why when I generate terrain with CTB and then load it in Cesium, tile coordinates doesn't match tile naming.
I mean, I use Cesium inspector on a tile with elevation in order to get it's coordinates (level, x and y) then I go in generated terrain directory in order to find corresponding tile but it doesn't exist. I can find `terrain/Z/X/` path but `Y.terrain` doesn't exist.
By the way, visually in Cesium there is obviously no problem with elevation georeferencing.

Could someone explain me?

**Comment by homme** [comment]
I'm guessing this was a mismatch between the tileset that was loaded and the tileset that was generated?  If it's still an issue feel free to reopen...

**Comment by Jule-** [comment]
It seems that Cesium map its "terrain tile coordinates" on raster input rather than elevation model input. This could explain the mismatch between global-geodetic (heightmap-1.0) and mercator (raster) tile coordinates in my case.

See tile **L11X2430Y719**:
![level_11](https://cloud.githubusercontent.com/assets/9716736/7302260/612bfb46-e9e8-11e4-8296-241bf7d3970c.jpg)

Which is not present in the loaded terrain folder:
![folder](https://cloud.githubusercontent.com/assets/9716736/7302265/68809ef6-e9e8-11e4-831a-fddf4b12bfb1.jpg)
No tile starting by "7"... It seems there is a factor of almost 2 on **Y** coordinate which make me think about a tileset mismatch.

**But**, when we zoom out for the level 0 it seems that it is a global-geodetic tileset, which is the reason of my confusion:
![level_0](https://cloud.githubusercontent.com/assets/9716736/7302273/7e75f5da-e9e8-11e4-8628-5d88775ddaed.jpg)

Can't understand how Cesium handle this tile coordinate display!
I don't know if it is necessary to reopen this issue because I don't think it is an CTB issue... But the issue still exists.
