### ISSUE TITLE
Getting error on obtaining terrain tiles

### ISSUE THREAD

**Issue by bik20** [geo-data/cesium-terrain-builder#16]
Hi,
I had built tiles in the format of .terrain. I had included layer.json file and enabled CORS. But I am getting error on using these lines of codes in sandcastle -
  var viewer = new Cesium.Viewer('cesiumContainer');
    var terrainProvider = new Cesium.CesiumTerrainProvider({
        url : 'http://localhost:8080/cesium/Apps/Sandcastle/terrain/tiles'   // I had also checked with relative URL
    });
    viewer.scene.terrainProvider = terrainProvider;

Errors are - 
An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 1 Y: 0 Level: 0.
An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 0 Y: 0 Level: 0.

Note: I am having 0/0/0.terrain and 0/1/0.terrain

**Comment by gberaudo** [comment]
You might be serving gzipped terrain with an incorrect content encoding.
See http://en.wikipedia.org/wiki/HTTP_compression.

**Comment by homme** [comment]
If @gberaudo's suggestion doesn't work, then try testing the tiles using [Cesium Terrain Server](https://github.com/geo-data/cesium-terrain-server) which is designed to address these kind of wrinkes when developing tilesets. If the tileset still plays up then we can investigate further.
