### ISSUE TITLE
Error when parsing terrain tiles

### ISSUE THREAD

**Issue by turban** [geo-data/cesium-terrain-builder#2]
I've created a tileset and added the missing top tile: 
https://github.com/geo-data/cesium-terrain-builder/issues/1

Unfortunately, I'm still getting an error:
An error occurred in "CesiumTerrainProvider": Failed to obtain terrain tile X: 1 Y: 0 Level: 0. 

This tile is generated by the terrain builder, and the URL is correct, but it seems to fail in the createHeightmapTerrainData method of CesiumTerrainProvider. An error occurs in this line:

var heightBuffer = new Uint16Array(buffer, 0, provider._heightmapWidth \* provider._heightmapWidth);

I wonder if there is something wrong in the buffer obtained from the file. buffer.byteLength is 48, while provider._heightmapWidth \* provider._heightmapWidth is 4225. Isn't the buffer too short?  

This is the tile: 
http://thematicmapping.org/data/tiles/terrain/jotunheimen/0/1/0.terrain

**Comment by zhali** [comment]
hi, i am gis programmer from china, also meet this problem:
      i have request the terrain file and layer.json ,but error occurred in "CesiumTerrainProvider":      Failed to obtain terrain tile X: 1 Y: 0 Level: 0.
can not open this ur:lhttps://groups.google.com/d/msg/cesium-dev/tE7AuARBOQQ/iAGS2fzQH-wJ
not clear how to :
    So I created a .htaccess file with these lines:
    AddType application/octet-stream terrai
    AddEncoding gzip terrain
could you give me some tips, thank you!

**Comment by zhali** [comment]
i'm using tomcat 7.0 to publish the terrain files
