### ISSUE TITLE
elevation is too high by roughly 30m

### ISSUE THREAD

**Issue by erahhal** [geo-data/cesium-terrain-builder#22]
I'm using the NED 1/3 arc second data set to generate tiles to zoom level 15 for Cape Canaveral in Florida, and finding that the terrain looks accurate in shape, but the elevation is too high by about 30m.   The Cesium AGI STK World Terrain set uses NED data as well, and I can see the exact same artifacts and characteristics in the terrain I'm generating as that in the AGI data, except for the elevation difference.  Is there a parameter I'm missing when generating terrain tiles?

edit: actually it seems to be exactly 30m.

**Comment by erahhal** [comment]
Was able to figure this out.  It turns out that the NED data is using a different vertical datum than that expected by Cesium.  I used the following tool to convert the vertical datum:

http://vdatum.noaa.gov/

**Comment by homme** [comment]
@erahhal I'm glad you figured it out.  I haven't had to use tiles for any application sensitive to absolute height - relative has been fine so far! What is the vertical datum used by Cesium out of interest?  I'll note it in the documentation...

**Comment by homme** [comment]
According to the [CesiumTerrainProvider](http://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html) source code, it's just WGS84.  If your source data was specified as being in NED, it's interesting that GDAL (used by cesium terrain builder under the hood) didn't correctly translate the vertical datum.

**Comment by homme** [comment]
According to the [CesiumTerrainProvider](http://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html) source code, it's just WGS84.  If your source data was specified as being in NED, it's interesting that GDAL (used by cesium terrain builder under the hood) didn't correctly translate the vertical datum.
