### ISSUE TITLE
no "ctb/TileCoordinateIterator.hpp" in ctb.hpp

### ISSUE THREAD

**Issue by Universefei** [geo-data/cesium-terrain-builder#25]
![image](https://cloud.githubusercontent.com/assets/4932234/9061493/abbe4e0a-3aee-11e5-907e-fecff0718d3c.png)
can not find "ctb/TileCoordinateIterator.hpp" in Source files and cmakelists.

**Comment by homme** [comment]
Thanks, the above commit should have fixed this.
