### ISSUE TITLE
Does not compile on Mac OS X Mavericks (clang)

### ISSUE THREAD

**Issue by thhomas** [geo-data/cesium-terrain-builder#3]
Many errors when trying to build on mavericks:
- does not like use of ostringstream like ctb-extents.cpp:148, ctb-tile.cpp:184, ctb-tile.cpp:194, ctb-tile.cpp:207, ctb-tile.cpp:216
error:
 cesium-terrain-builder-master/tools/ctb-extents.cpp:148:66: error: cannot take the address of an rvalue of type 'std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
  const string filename = dirname + static_cast<ostringstream*>( &(ostringstream() << zoom << ".geojson") )->str();
- problem in instantiation of function template specialization package_task:
ctb-tile.cpp:460:48: note: in instantiation of function template specialization
      'std::__1::packaged_task<int (TerrainBuild *, ctb::Grid *)>::packaged_task<int (&)(TerrainBuild *, ctb::Grid *), void>' requested here
    packaged_task<int(TerrainBuild *, Grid *)> task($runTiler); // wrap the function

**Comment by tmizu23** [comment]
I success the compile changing the code.
for example, I change the error code of tools/ctb-extents.cpp like this.
```
const string filename = dirname + (ostringstream() << zoom << ".geojson").str();
```
the error of ctb-tile.cpp is also the same.

**Comment by homme** [comment]
@tmizu23 Thanks you. Are you able to provide a pull request for your changes?

**Comment by homme** [comment]
Feel free to re-open this issue if additional improvements are required.
