### ISSUE TITLE
Install fails with custom gdal build

### ISSUE THREAD

**Issue by mamayoleksandr** [geo-data/cesium-terrain-builder#30]
make[2]: *** No rule to make target `/Users/mamay/custombuilds/lib/libgdal.so', needed by `src/libctb.dylib'.  Stop.
make[1]: *** [src/CMakeFiles/ctb.dir/all] Error 2
make: *** [all] Error 2

**Comment by mamayoleksandr** [comment]
OS: MAC osx el capitan

build command:

cmake -DGDAL_INCLUDE_DIR=/Users/mamay/custombuilds/include -DGDAL_LIBRARY=/Users/mamay/custombuilds/lib/libgdal.so -DGDAL_LIBRARY_DIR=/Users/mamay/custombuilds/lib/ -DCMAKE_INSTALL_PREFIX=/Users/mamay/custombuilds ..

**Comment by homme** [comment]
Hi - I'll prefix this by saying that unfortunately we don't support OSX: however patches are welcome!  Having said that, the message

    make[2]: *** No rule to make target /Users/mamay/custombuilds/lib/libgdal.so', needed 

usually means that the the file `/Users/mamay/custombuilds/lib/libgdal.so` doesn't exist.  Could you double check this?

**Comment by mamayoleksandr** [comment]
Hi homme,

You are right, there is no such file /Users/mamay/custombuilds/lib/libgdal.so, it is supposed to be custom goal build.
So far we can use the docker build, so it is not critical, but for curiosity sake, any ideas why libgdal.so was not installed there?

**Comment by homme** [comment]
@mamayoleksandr without knowing how GDAL was installed, I can't say why (the rather critical) `libgdal.so` is not present.  I can only suggest re-installing GDAL (presumably it is installed from source, as it is a custom build) and ensuring that GDAL's `./configure` is  called with `--prefix=/Users/mamay/custombuilds`.  You can also look at the output of `make install` to see where files are installed.
