### ISSUE TITLE
Blocky terrain

### ISSUE THREAD

**Issue by turban** [geo-data/cesium-terrain-builder#4]
The terrain rendered with Cesium Terrain Builder gets a bit blocky. See the mountain terraces in the hillside. 

![screen shot 2014-10-12 at 12 36 51](https://cloud.githubusercontent.com/assets/548708/4605803/db8744fc-51fb-11e4-9dde-444e73c258e3.png)

Are the height values rounded?

**Comment by ppershing** [comment]
Hi homme, I have the same problem. I built terrain using the latest docker image and using 1" DEM of Swiss Alps (http://www.viewfinderpanoramas.org/dem3.html#alps), letting `cbt-tile` decide on the maximum zoom level.

![image](https://cloud.githubusercontent.com/assets/837681/6979901/73e5f9ca-d9ea-11e4-90af-a4bdc566e556.png)

Is there any way I could help debugging the issue?

**Comment by ppershing** [comment]
I tested upsampling the underlying dataset as follows
```gdalwarp -tr 0.0001 0.0001 combined.vrt combined2.vrt -of VRT -overwrite -r cubic``` 
(this should give a precision around 0.4 arc second) and generated the tiles from this new dataset limiting the maxzoom to 14. So far the results look promising and it should be a decent workaround.
@homme would it be possible to add a native support for (cubic) interpolation when building the tiles?

**Comment by homme** [comment]
@ppershing many thanks for taking the time to test this.  Your workaround sounds good.  I'm adding a command line option to `ctb-tile` to enable the resampling algorithm to be specified, which will hopefully mean that we won't need your workaround.  At the moment the resampling algorithm is 'nearest neighbour'.  It was suggested by the GDAL maintainer (Even Rouault) that we use 'average' as he thinks this should work better when resampling to lower resolutions: this will be the new default.  If one of the other methods, such as 'cubic', proves to produce better results then I can always change the default.

**Comment by homme** [comment]
The resampling options are available in the [`homme/cesium-terrain-builder:latest`](https://registry.hub.docker.com/u/homme/cesium-terrain-builder/) docker image.

**Comment by homme** [comment]
I can confirm that the 'average' resampling option has produced good results with no more blocky terrain artefacts.

**Comment by turban** [comment]
![screen shot 2015-05-29 at 23 30 04](https://cloud.githubusercontent.com/assets/548708/7893168/5c7d54fc-065b-11e5-87ae-ccc0099353f2.png)

Great! I can also confirm that my terrain is no longer blocky. Sometimes average is best :-)

**Comment by homme** [comment]
@turban Definitely! And I will be paying much more attention to resampling algorithms in the future :)

**Comment by chabok** [comment]
Hi Homme, 
I know this issue is closed but I get blocky terrain effect even after using average re-sampling as per described here. Have attached screenshot and actual DSM file to double check just in case I'm missing anything! Please rename .txt to zip to open the files.
Thanks:) 
Adam

[Tiff.txt](https://github.com/geo-data/cesium-terrain-builder/files/42568/Tiff.txt)
