### ISSUE TITLE
The code is not compatible with GDAL 2.2, and can compile with GDAL 2.1

### ISSUE THREAD

**Issue by fangd123** [geo-data/cesium-terrain-builder#51]
When I use the `GDAL 2.2.1` to compile the source, it reported an error like `GDALCreateOverviewDataset() has the wrong number of arguments`, I query the header file, the function of `GDAL 2.2.1` has just three arguments instead of four. 

And then I download the source code of `GDAL 2.1.4`, the CTB has built succefully.

**Comment by mrgloom** [comment]
For cesium-terrain-builder we need GDAL version >= 2.0.0

```
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
sudo apt update
sudo apt install -y gdal-bin python-gdal libgdal-dev
```

**Comment by mrgloom** [comment]
Related 
https://github.com/geo-data/cesium-terrain-builder/issues/15
