### ISSUE TITLE
An error occurred in "T": Failed to obtain terrain tile

### ISSUE THREAD

**Issue by CosmosEcho** [geo-data/cesium-terrain-builder#62]
I use ctb to create terrain tiles, the format is quantized-mesh-1.0. There is an error when loaded with Cesium 1.41. Who dose knows the problem?
![image](https://user-images.githubusercontent.com/13760084/38792514-e5c1747a-417f-11e8-8984-287aa048483c.png)

**Comment by Cq5616** [comment]
i have got the same problem, do you know how to figure it out?
