### ISSUE TITLE
Layer.json is not generated with ctb-tile, should it?

### ISSUE THREAD

**Issue by Crare** [geo-data/cesium-terrain-builder#73]
Hi,
I'm running the ctb-tile command to generate .terrain files with the z/x/y folders from .tif-file.
My cesium terrain server is getting this error on browser:

> http://localhost:8082/tilesets/terrain/test/layer.json 404 (Not Found)

When I look at the folder, there is no layer.json. Should it be there?

I'm running both server and builder from latest docker containers.
"ctb-tile -V" gives me version "0.4.1".

**Comment by Crare** [comment]
ok I figured it out. you have to add "-l" in the ctb-tile cli..

**Comment by flyingsnowers** [comment]
hi:  how to add "-l" in the ctb-tile cli?

**Comment by ahuarte47** [comment]
Hi, you could read [here](https://github.com/tum-gis/cesium-terrain-builder-docker), it teaches you how to do it.
