### ISSUE TITLE
Error while running make install

### ISSUE THREAD

**Issue by ajinra020307** [geo-data/cesium-terrain-builder#93]
Error when running make install command
Iam using debian 10

```
/usr/bin/ld: ../src/libctb.so: undefined reference to `GDALCreateOverviewDataset(GDALDataset*, int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/ctb-export.dir/build.make:88: tools/ctb-export] Error 1
make[1]: *** [CMakeFiles/Makefile2:203: tools/CMakeFiles/ctb-export.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by gberaudo** [comment]
@ajinra020307 this error does not appear in the branch in https://github.com/geo-data/cesium-terrain-builder/pull/64.
I guess there is a fix for this in that branch.

**Comment by ajinra020307** [comment]
okay,thank you

**Comment by ajinra020307** [comment]
I tried the same with #64 again same error

/usr/bin/ld: ../src/libctb.so: undefined reference to `GDALCreateOverviewDataset(GDALDataset*, int, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/CMakeFiles/ctb-export.dir/build.make:88: tools/ctb-export] Error 1
make[1]: *** [CMakeFiles/Makefile2:208: tools/CMakeFiles/ctb-export.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by ajinra020307** [comment]
sorry, it worked, i tried without switching brach
