### ISSUE TITLE
Possibility to merge several regions with different resolutions?

### ISSUE THREAD

**Issue by lukey78** [geo-data/cesium-terrain-builder#97]
In the process of building a global terrain model, I have the whole world in low resolution (30-50m) and some regions in much higher resolutions. Does anyone know of a good way to create the terrain tiles for something like this without continously running into "integer overflow" or memory errors?

I thought that it could be possible to generate the quantized mesh tiles for certain regions (e.g. a single country), which also creates the layer.json file perfectly. 

I thought I could do this for each country I have better resolutions available, and then merge this with the terrain generated with a "global" low-res DEM. 

Is it possible to merge individually generated terrain files (and layer.json files) into a new one?

Currently, if I have a workflow for building all meshes for the whole world (by using VRT etc.) it may happen that the server calculates for 14 days and then crashes at 80% or so. Generating individual regions and merge them later might be a better option.

**Comment by BWibo** [comment]
This might contain some helpful advice:
https://github.com/tum-gis/cesium-terrain-builder-docker/issues/3
